### ISSUE TITLE
git flow 관련 질문

### ISSUE THREAD

**Issue by semilaver** [Gaship/gaship-shopping-mall#18]
도메인 없이 feature/gradehistory/base 로 처음에 진행하고 base 에서 바로 dev 로 pr 올렸는데 아직 merge 는 안한 상태라
해당 pr close 해버리고 도메인 브랜치 feature/gradehistory 딴후에 해당 브랜치로 Pr 해서 머지하고 conflict 해결 후에 도메인 브랜치에서 다시 dev 로 pr 올려서 머지시키는게 좋을까요??

**Comment by HoFe-U** [comment]
feature/gradehistory 가 안파질겁니다  아마 이미있다는 오류가 생길거에요 그래서 복수형으로 파서 해당 브랜치로 PR 해서 머지하시고 이후 작업다 끝나시면 dev 로 PR 하시면 될것같습니다.

**Comment by semilaver** [comment]
해결 완료되었습니다. 감사합니다:)
